# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: personalkrarrobo
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: todoapp
# "service" is the name of this project. This will also be added to your AWS resource names.
service: todo-app

provider:
  name: aws
  runtime: nodejs18.x

functions:
  api:
    handler: src/lambda.handler
    events:
      - http:
          path: /api/{proxy+}
          method: any
          cors: true
      # - http:
      #     path: /swagger
      #     method: get
      #     cors: true
      # - http:
      #     path: /swagger.json
      #     method: get
      #     cors: true

plugins:
  - serverless-plugin-typescript
  - serverless-offline

custom:
  serverlessPluginTypescript:
    tsConfigFileLocation: './tsconfig.json'